### PR TITLE
Slicer Gui

### LINKED ISSUE #9: Leftover files seemingly unclear as to what regions are unused
Here's a 1.20.1 inventory.png over which I have artisanally scribbled:
inventory

The output files are pretty much as expected - the normal vanilla files, plus whatever the scribble changed. Notably, nothing outside of the inventory window is carried over into the new copy of inventory.png.
inventory
effect_background_large
effect_background_small
effect_background
effect_background_ambient

My issue is with the leftovers files, which indicate which parts of a file were split into other files. In the case of inventroy.png and quite a few others, the entire file has a red tint, which is unexpected since, as mentioned previously, all of the empty transparent space in the outer reaches of inventory.png isn't used anywhere in game and isn't carried over into the newly split version of inventory.png.
inventory

For comparison, here are copies of icons.png and widgets.png's remainder files, as they appear when you use slicer on default vanilla assets. In this case, none of that unused outer blank area is tinted red, because none of it is actually used. This is what I'd expect for the blank area outside of inventory.png as well, but that isn't the case. Am I misunderstanding what the red shading is supposed to mean, or is this indeed incorrect behaviour?
icons
widgets

### PR DESCRIPTION
**Pull request by satanicantichrist**
This PR add GUI to the slicer tools to be more user friendly.
To run CLI version (Current one) run it as now from terminal with all arguments.
To run the GUI run the jar file without any arguments.

Other stuff in the PR:

- Updated gradlew
- Fixes https://github.com/Mojang/slicer/issues/9
- Updated readme

image

### CODE REVIEW

**Comment by lowercasebtw** [comment]
whats it look like

**Comment by satanicantichrist** [comment]
> whats it look like

Yeah, forgot to show it, now its there

**Comment by lowercasebtw** [comment]
noice

**Comment by slicedlime** [comment]
From README:
> This tool is provided as reference code to help update existing resource packs for Minecraft: Java Edition, and as such we are not accepting contributions or actively maintaining it.

**Comment by lowercasebtw** [comment]
booo

**Comment by blryface** [comment]
Cool tool, since it's MIT you can just release it as your own tool

**Comment by blryface** [comment]
..ah yes, MIT, ARR.

**Comment by lowercasebtw** [comment]
lol

**Pull request closed without merging**
